styling css
ahmadaidil/reax-select pull request #1
Opened 2019-04-22 04:22 UTC by elishaenu

untuk multiselect, belum remove option yang di select.
untuk format style sudah dicek afi dan approved. thankyou @ahmadaidil

2019-04-22 08:40 UTC, ahmadaidil requested changes

2019-04-22 08:40 UTC, ahmadaidil commented on src/value.js
> +import { ArrowDropupIcon, ArrowDropdownIcon } from 'volantis-icon'
ubah jadi bukan import destruct tapi from 'volantis-icon/dist/icons/xxx'

2019-04-22 08:47 UTC, elishaenu commented on src/value.js
> +import { ArrowDropupIcon, ArrowDropdownIcon } from 'volantis-icon'
udah bosque @ahmadaidil makasih

2019-04-23 12:29 UTC, ahmadaidil approved these changes

2019-04-23 12:29 UTC, merged